// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: funds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const createFund = `-- name: CreateFund :one
INSERT INTO funds (name, vintage_year, target_size_usd, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, vintage_year, target_size_usd, status, created_at
`

type CreateFundParams struct {
	Name          string          `json:"name"`
	VintageYear   int32           `json:"vintage_year"`
	TargetSizeUSD decimal.Decimal `json:"target_size_usd"`
	Status        string          `json:"status"`
}

func (q *Queries) CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error) {
	row := q.db.QueryRowContext(ctx, createFund,
		arg.Name,
		arg.VintageYear,
		arg.TargetSizeUSD,
		arg.Status,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUSD,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const fundExists = `-- name: FundExists :one
SELECT EXISTS (
    SELECT 1
    FROM funds
    WHERE id = $1
)
`

func (q *Queries) FundExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, fundExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFund = `-- name: GetFund :one
SELECT id, name, vintage_year, target_size_usd, status, created_at
FROM funds
WHERE id = $1
`

func (q *Queries) GetFund(ctx context.Context, id uuid.UUID) (Fund, error) {
	row := q.db.QueryRowContext(ctx, getFund, id)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUSD,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listFunds = `-- name: ListFunds :many
SELECT id, name, vintage_year, target_size_usd, status, created_at
FROM funds
ORDER BY created_at DESC
`

func (q *Queries) ListFunds(ctx context.Context) ([]Fund, error) {
	rows, err := q.db.QueryContext(ctx, listFunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fund
	for rows.Next() {
		var i Fund
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VintageYear,
			&i.TargetSizeUSD,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFund = `-- name: UpdateFund :one
UPDATE funds
SET name = $2,
    vintage_year = $3,
    target_size_usd = $4,
    status = $5
WHERE id = $1
RETURNING id, name, vintage_year, target_size_usd, status, created_at
`

type UpdateFundParams struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	VintageYear   int32           `json:"vintage_year"`
	TargetSizeUSD decimal.Decimal `json:"target_size_usd"`
	Status        string          `json:"status"`
}

func (q *Queries) UpdateFund(ctx context.Context, arg UpdateFundParams) (Fund, error) {
	row := q.db.QueryRowContext(ctx, updateFund,
		arg.ID,
		arg.Name,
		arg.VintageYear,
		arg.TargetSizeUSD,
		arg.Status,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUSD,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
