// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInvestor = `-- name: CreateInvestor :one
INSERT INTO investors (name, investor_type, email)
VALUES ($1, $2, $3)
RETURNING id, name, investor_type, email, created_at
`

type CreateInvestorParams struct {
	Name         string `json:"name"`
	InvestorType string `json:"investor_type"`
	Email        string `json:"email"`
}

func (q *Queries) CreateInvestor(ctx context.Context, arg CreateInvestorParams) (Investor, error) {
	row := q.db.QueryRowContext(ctx, createInvestor, arg.Name, arg.InvestorType, arg.Email)
	var i Investor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvestorType,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getInvestor = `-- name: GetInvestor :one
SELECT id, name, investor_type, email, created_at
FROM investors
WHERE id = $1
`

func (q *Queries) GetInvestor(ctx context.Context, id uuid.UUID) (Investor, error) {
	row := q.db.QueryRowContext(ctx, getInvestor, id)
	var i Investor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvestorType,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const investorExists = `-- name: InvestorExists :one
SELECT EXISTS (
    SELECT 1
    FROM investors
    WHERE id = $1
)
`

func (q *Queries) InvestorExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, investorExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvestors = `-- name: ListInvestors :many
SELECT id, name, investor_type, email, created_at
FROM investors
ORDER BY created_at DESC
`

func (q *Queries) ListInvestors(ctx context.Context) ([]Investor, error) {
	rows, err := q.db.QueryContext(ctx, listInvestors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investor
	for rows.Next() {
		var i Investor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InvestorType,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
