// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (investor_id, fund_id, amount_usd, investment_date)
VALUES ($1, $2, $3, $4)
RETURNING id, investor_id, fund_id, amount_usd, investment_date
`

type CreateInvestmentParams struct {
	InvestorID     uuid.UUID       `json:"investor_id"`
	FundID         uuid.UUID       `json:"fund_id"`
	AmountUSD      decimal.Decimal `json:"amount_usd"`
	InvestmentDate time.Time       `json:"investment_date"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRowContext(ctx, createInvestment,
		arg.InvestorID,
		arg.FundID,
		arg.AmountUSD,
		arg.InvestmentDate,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.InvestorID,
		&i.FundID,
		&i.AmountUSD,
		&i.InvestmentDate,
	)
	return i, err
}

const listInvestmentsByFund = `-- name: ListInvestmentsByFund :many
SELECT id, investor_id, fund_id, amount_usd, investment_date
FROM investments
WHERE fund_id = $1
ORDER BY investment_date DESC, id DESC
`

func (q *Queries) ListInvestmentsByFund(ctx context.Context, fundID uuid.UUID) ([]Investment, error) {
	rows, err := q.db.QueryContext(ctx, listInvestmentsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.InvestorID,
			&i.FundID,
			&i.AmountUSD,
			&i.InvestmentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
