// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

type Fund struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	VintageYear   int32           `json:"vintage_year"`
	TargetSizeUSD decimal.Decimal `json:"target_size_usd"`
	Status        string          `json:"status"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Investment struct {
	ID             uuid.UUID       `json:"id"`
	InvestorID     uuid.UUID       `json:"investor_id"`
	FundID         uuid.UUID       `json:"fund_id"`
	AmountUSD      decimal.Decimal `json:"amount_usd"`
	InvestmentDate time.Time       `json:"investment_date"`
}

type Investor struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	InvestorType string    `json:"investor_type"`
	Email        string    `json:"email"`
	CreatedAt    time.Time `json:"created_at"`
}
